config/routes.rb
Rails.application.routes.draw do
  # Accueil
  root 'gossips#index'

  # REST routes
  resources :gossips
  resources :users
  resources :cities, only: [:show]
  resources :comments
  resources :sessions, only: [:new, :create, :destroy]
  resources :likes, only: [:create, :destroy]
  
  
  # menu (static pages)
  get 'welcome/:user_entry', to: 'welcome#show', as: 'user_entry'
  get '/team', to: 'static_pages#team'
  get '/contact', to: 'static_pages#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
  validates :zip_code,
    format: { with: /\A(([0-8][0-9])|(9[0-5])|(2[ab]))[0-9]{3}\z/, message: "please enter a valid french zip code" }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/gossip.rb
class Gossip < ApplicationRecord 
  belongs_to :user
  has_many :gossip_tags
  has_many :tags, through: :gossip_tags
  has_many :comments
  has_many :likes, as: :reference
  validates :title,
    presence: true,
    length: { in: 3..30 }
  validates :content,
    presence: true,
    length: { in: 3..150 }
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
  validates_presence_of :value, :user, :gossip
  validates :user_id, uniqueness: { scope: [:gossip_id] }
  validates :value, inclusion: 0..4
end
 

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossip_tags
  has_many :gossips, through: :gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  has_many :comments
  has_many :likes, dependent: :destroy
  has_secure_password
  validates :password,
    presence: true,
    length: {minimum: 6}
#  validates :password_confirmation,
#    presence: true
  validates :first_name,
    length: { minimum: 2 }
  validates :last_name,
    length: { minimum: 2 }
  validates :email,
    presence: true,
    uniqueness: true,
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }

    def full_name
      "#{first_name} #{last_name}"
    end


  end 

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user, only: [:new, :create, :update, :destroy]
 
 
  def new
    @like = Like.new
  end

  def index
    @like = Like.all
  end

  
  def create
    @like = Like.new(value: params[:value], gossip_id: params[:gossip], user: current_user)
      if @like.save
        flash[:success] = "Merci d'avoir liké!"
      else
        flash[:error] = @like.errors.full_messages.join(', ')
      end
  end
   
  def destroy
    @like = Like.find(params[:id])
  private
  end

  def like_params
    params.require(:like).permit(:value, :user_id, :gossip_id)
  end
  
  def authenticate_user
    unless current_user
      flash[:error] = "Vous devez vous connecter pour accéder au contenu."
      redirect_to new_session_path
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(first_name: user_params[:first_name],last_name: user_params[:last_name], city: City.find(params[:city]), email: user_params[:email], password: user_params[:password])
    if @user.save
      log_in(@user)
      flash[:success] = "Ton profil a bien été créé ! "
      redirect_to gossips_path
    else
      messages = []
      if @user.errors.any? 
          @user.errors.full_messages.each do |message| 
          messages << message
        end 
        flash[:error] = "Erreur jeune comère, ton profil n'a pas été créé parce que :#{messages.join(" ")}"
      end
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @user = User.all
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when 'notice' then "alert alert-info"
      when 'success' then "alert alert-success"
      when 'error' then "alert alert-danger"
      when 'alert' then "alert alert-warning"
    end
  end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def current_user
    User.find_by(id: session[:user_id])
  end

   def log_in(user)
    session[:user_id] = user.id
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user?(user)
    user == current_user
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Fontawesome incons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.css"></link>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>The Fucking Gossip Project</title>
  </head>

  <body>

  <header>
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #ffc0cb;">
    <a class="navbar-brand">The Gossip Project</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav nav-left">
        <li class="nav-item">
        <a class="nav-link" href="/gossips">Accueil</a>
        </li>
        <li class="nav-item">
          <%= link_to "La Team", team_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contact", contact_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
        <% if signed_in? %>
           <%= link_to "#{current_user.full_name}", user_path(current_user),class:"nav-link"%>
        <%end%>
        </li>

      </ul>
    
      <div class="nav-item d-flex flex-row-reverse">
        <ul class="navbar-nav">
          <% if signed_in? %>
          <li class="btn btn-danger"><%= link_to "Se déconnecter", session_path(session.id), method: :delete, style: 'color:#FFFFFF;' %></li>
          <% else %>
            <div class="dropdown show">
              <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                S'inscrire / Se connecter
              </a>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <a class="dropdown-item" href=<%= new_user_path %>>S'inscrire</a>
              <a class="dropdown-item" href=<%= new_session_path %>>Se connecter</a>
              </div>
            </div>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %>">
        <%= value %>
  </div>
<% end %>

  
    <%= yield %>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

<!-- <div class="alert alert-success" role="alert">-->
<!--   <%= flash[:success] %>-->
<!-- </div>-->
<!-- <div class="alert alert-danger" role="alert">-->
<!--   <%= flash[:failure] %>-->
<!-- </div>-->